"""
Test client for MCP contract servers generated by agentic_implementation.py

This script demonstrates how to programmatically interact with MCP servers
without using the interactive chatbot. Useful for:
- Testing contract functions
- Automated workflows
- Integration with other systems
- Batch operations
"""

import asyncio
from fastmcp import Client
from pathlib import Path
import json
import sys


async def test_mcp_server(mcp_server_path: str, contract_type: str = "unknown"):
    """
    Test a generated MCP contract server.
    
    Args:
        mcp_server_path: Path to the MCP server file (e.g., output/Investment_Agreement_1/BlockChain_Venture_Ca_mcp_server.py)
        contract_type: Type of contract for context
    """
    
    print(f"\n{'='*70}")
    print(f"MCP SERVER TEST: {Path(mcp_server_path).stem}")
    print(f"Contract Type: {contract_type}")
    print(f"{'='*70}\n")
    
    client = Client(mcp_server_path)
    
    try:
        async with client:
            # 1. Sanity check - verify connection
            print("✓ Testing connection...")
            await client.ping()
            print("✓ Connected to MCP server\n")
            
            # 2. List available tools (contract functions)
            print("📋 Listing available contract functions...")
            tools = await client.list_tools()
            print(f"✓ Found {len(tools)} functions:\n")
            
            # Categorize tools by type
            payable_functions = []
            view_functions = []
            state_functions = []
            
            for tool in tools:
                name = tool.get('name', 'unknown')
                state = tool.get('stateMutability', 'nonpayable')
                description = tool.get('description', 'No description')
                
                print(f"  • {name}")
                print(f"    Type: {state}")
                print(f"    Description: {description}\n")
                
                if state == 'payable':
                    payable_functions.append(name)
                elif state in ['view', 'pure']:
                    view_functions.append(name)
                else:
                    state_functions.append(name)
            
            print(f"\nFunction Categories:")
            print(f"  - Payable (send funds): {len(payable_functions)} functions")
            print(f"  - View/Query (read-only): {len(view_functions)} functions")
            print(f"  - State-changing: {len(state_functions)} functions")
            
            # 3. Test view functions first (safe to call)
            print(f"\n{'='*70}")
            print("TESTING VIEW FUNCTIONS (Read-Only Queries)")
            print(f"{'='*70}\n")
            
            if view_functions:
                for func_name in view_functions[:3]:  # Test first 3
                    try:
                        print(f"🔍 Calling: {func_name}()")
                        result = await client.call_tool(func_name, {})
                        print(f"   ✅ Result: {json.dumps(result, indent=2)[:200]}...\n")
                    except Exception as e:
                        print(f"   ❌ Error: {e}\n")
            else:
                print("ℹ️  No view functions available\n")
            
            # 4. Test state-changing functions (demonstration only)
            print(f"{'='*70}")
            print("STATE-CHANGING FUNCTIONS (Demonstration)")
            print(f"{'='*70}\n")
            
            if state_functions:
                print(f"Available state-changing functions: {', '.join(state_functions[:5])}")
                print("\n⚠️  WARNING: These functions modify contract state and require valid parameters.")
                print("To call these, provide appropriate values in the test script.\n")
                
                # Example: Try calling with minimal args (will fail gracefully)
                func_name = state_functions[0]
                try:
                    print(f"Attempting test call to {func_name}()...")
                    result = await client.call_tool(func_name, {})
                    print(f"Result: {result}")
                except Exception as e:
                    print(f"Expected error (no parameters provided): {type(e).__name__}")
                    print(f"Message: {str(e)[:100]}...\n")
            else:
                print("ℹ️  No state-changing functions available\n")
            
            # 5. Test payable functions (demonstration only)
            print(f"{'='*70}")
            print("PAYABLE FUNCTIONS (Require Funds)")
            print(f"{'='*70}\n")
            
            if payable_functions:
                print(f"Available payable functions: {', '.join(payable_functions[:5])}")
                print("\n⚠️  WARNING: These functions send ETH/funds and cost gas.")
                print("Ensure contract is deployed and you have sufficient funds.\n")
            else:
                print("ℹ️  No payable functions available\n")
            
            # 6. Summary report
            print(f"{'='*70}")
            print("TEST SUMMARY")
            print(f"{'='*70}")
            print(f"✅ MCP Server is operational")
            print(f"✅ Total functions: {len(tools)}")
            print(f"✅ View functions tested: {min(3, len(view_functions))}")
            print(f"✅ Connection: Active\n")
            
            return True
            
    except FileNotFoundError:
        print(f"❌ Error: MCP server file not found: {mcp_server_path}")
        return False
    except Exception as e:
        print(f"❌ Error connecting to MCP server: {e}")
        import traceback
        traceback.print_exc()
        return False


async def test_multiple_servers(output_dir: str = "./output"):
    """
    Test all MCP servers in the output directory.
    
    Args:
        output_dir: Path to output directory containing generated contracts
    """
    
    print("\n" + "="*70)
    print("TESTING ALL MCP SERVERS")
    print("="*70)
    
    output_path = Path(output_dir)
    
    if not output_path.exists():
        print(f"❌ Output directory not found: {output_dir}")
        return
    
    # Find all MCP server files
    mcp_servers = list(output_path.glob("*/*_mcp_server.py"))
    
    if not mcp_servers:
        print(f"❌ No MCP servers found in {output_dir}")
        print("   Run agentic_implementation.py first to generate servers.")
        return
    
    print(f"\nFound {len(mcp_servers)} MCP server(s):\n")
    
    results = {}
    
    for i, mcp_path in enumerate(mcp_servers, 1):
        # Extract contract type from parent directory
        contract_type = mcp_path.parent.name.rsplit('_', 1)[0]
        
        print(f"[{i}/{len(mcp_servers)}] Testing: {mcp_path.parent.name}")
        success = await test_mcp_server(str(mcp_path), contract_type)
        results[str(mcp_path)] = success
        
        if i < len(mcp_servers):
            print("\n" + "-"*70 + "\n")
    
    # Final summary
    print("\n" + "="*70)
    print("OVERALL SUMMARY")
    print("="*70)
    successful = sum(1 for v in results.values() if v)
    print(f"✅ Successful: {successful}/{len(results)}")
    print(f"❌ Failed: {len(results) - successful}/{len(results)}\n")


def main():
    """Main entry point"""
    
    print("IBM Agentics - MCP Server Test Client")
    print("=" * 70)
    
    if len(sys.argv) > 1:
        # Test specific server
        mcp_server_path = sys.argv[1]
        contract_type = sys.argv[2] if len(sys.argv) > 2 else "unknown"
        
        asyncio.run(test_mcp_server(mcp_server_path, contract_type))
    
    elif len(sys.argv) > 2 and sys.argv[1] == "--all":
        # Test all servers in output directory
        output_dir = sys.argv[2] if len(sys.argv) > 2 else "./output"
        asyncio.run(test_multiple_servers(output_dir))
    
    else:
        # Interactive mode
        print("\nUsage:")
        print("  # Test specific server:")
        print("  python test_client.py <path_to_mcp_server.py> [contract_type]")
        print("\n  Example:")
        print("  python test_client.py './output/Investment_Agreement_1/BlockChain_Venture_Ca_mcp_server.py' investment")
        print("\n  # Test all servers in output directory:")
        print("  python test_client.py --all [output_dir]")
        print("\n  Example:")
        print("  python test_client.py --all ./output")
        print("\nNote: Ensure MCP servers are generated first by running agentic_implementation.py\n")


if __name__ == "__main__":
    main()
